// ignore_for_file: non_constant_identifier_names, file_names

List Deals = [
  {
    "Name": "Deal1",
    "Price": 100,
    "Desc": "Fruit Package 1 | 1 Bundle",
    "Qty": 0,
    "InCart": false,
    "IsFav": false,
    "Image": Null,
    "Category": "Deals",
  },
  {
    "Name": "Deal2",
    "Price": 200,
    "Desc": "Snacks Package 1 | 1 Bundle",
    "Qty": 0,
    "InCart": false,
    "IsFav": false,
    "Image": Null,
    "Category": "Deals",
  },
  {
    "Name": "Deal3",
    "Price": 300,
    "Desc": "Vegetable Package 1 | 1 Bundle",
    "Qty": 0,
    "InCart": false,
    "IsFav": false,
    "Image": Null,
    "Category": "Deals",
  },
  {
    "Name": "Deal4",
    "Price": 400,
    "Desc": "Meat Package 1 | 1 Bundle",
    "Qty": 0,
    "InCart": false,
    "IsFav": false,
    "Image": Null,
    "Category": "Deals",
  },
  {
    "Name": "Deal5",
    "Price": 500,
    "Desc": "Fish Package 1 | 1 Bundle",
    "Qty": 0,
    "InCart": false,
    "IsFav": false,
    "Image": Null,
    "Category": "Deals",
  },
];
