List Fish = [
  {
    "Name": "Large Fish",
    "Price": 150,
    "Desc": "This is a large fish",
    "Qty": 0,
    "IsFav": false,
    "InCart": false,
    "Image": Null,
    "Category": "Fish",
  },
  {
    "Name": "Medium Fish",
    "Price": 100,
    "Desc": "This is a medium fish",
    "Qty": 0,
    "IsFav": false,
    "InCart": false,
    "Image": Null,
    "Category": "Fish",
  },
  {
    "Name": "Small Fish",
    "Price": 50,
    "Desc": "This is a small fish",
    "Qty": 0,
    "IsFav": false,
    "InCart": false,
    "Image": Null,
    "Category": "Fish",
  },
];
