List Vegetables = [
  {
    "Name": "Potato",
    "Price": 50,
    "Desc": "This is a potato",
    "Qty": 0,
    "IsFav": false,
    "InCart": false,
    "Image": Null,
    "Category": "Vegetables",
  },
  {
    "Name": "Tomato",
    "Price": 30,
    "Desc": "This is a tomato",
    "Qty": 0,
    "IsFav": false,
    "InCart": false,
    "Image": Null,
    "Category": "Vegetables",
  },
  {
    "Name": "Onion",
    "Price": 50,
    "Desc": "This is a onion",
    "Qty": 0,
    "IsFav": false,
    "InCart": false,
    "Image": Null,
    "Category": "Vegetables",
  },
];
